import { GameState } from "src/app/state/state";
import { CellData, GameStateDisplay, GameTypesKeys } from "./mineTypes";
 
//moving to actions.

export enum GameActionType {
  TOGGLE_LOST = "TOGGLE_LOST",
  SET_START = "TOGGLE_START",
  SET_END = "SET_END",
  UPDATE_UNCOVER_CELL = "UPDATE_UNCOVER_CELL",
  CHANGE_GAMESTATE_DISPLAY = "CHANGE_GAMESTATE_DISPLAY",
  INCREMENT_UNCOVER_CELL = "INCREMENT_UNCOVER_CELL",
  SET_UNCOVER_CELL = "SET_UNCOVER_CELL",
  INCREMENT_FLAGS_PLACED = "INCREMENT_FLAGS_PLACED",
  DECREMENT_FLAGS_PLACED = "DECREMENT_FLAGS_PLACED",
  CHOOSE_SIZE = "CHOOSE_SIZE",
  RESET_GAME = "RESET_GAME",
  SET_MINE_DATA = "SET_MINE_DATA",
  SET_MINE_DATA_OLDE = "SET_MINE_DATA_OLDE",
}
